### ISSUE TITLE
[Feat] (공용 컴포넌트) 뒤로가기, 닫기 네브바

### ISSUE THREAD

**Issue by Jiho31** [hinyc/wanted-codestates-project-10-9#12]
### TODO
- [x] 네비게이션 바 UI 구현
- [ ] 뒤로가기 버튼 클릭시 이전 페이지로 이동
- [ ] 닫기 버튼 클릭시 리뷰 목록 페이지로 이동 (?)
