### ISSUE TITLE
[Design] 그리드, 리스트 배열 선택 버튼, 리스트 최상위, 리뷰생성 버튼 디자인수정

### ISSUE THREAD

**Issue by hinyc** [hinyc/wanted-codestates-project-10-9#44]
### ISSUE
- Group: client
- Type: Design
- Detail: 버튼 디자인 디테일 추가

### TODO
 - [x] 그리드, 리스트 배열 호버효과추가(아래 선추가)
 - [x] 리스트 최상위 버튼 특정 스크롤위치에서 나타나도록  수정
 - [x] 리뷰생성 버튼 호버효과 부자연스러움 수정
